version: "3"
services:
  back-end:
    container_name: springboot-app
    build:
      context: back-end/songlist
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
        DB_URL: jdbc:mysql://mysql-db/songlist_db
        DB_USERNAME: unseenuser
        DB_PASSWORD: godblessyou
    depends_on:
      - my-mysql
    networks:
      - spring-mysql
  front-end:
    container_name: react-app
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - back-end
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./nginx/conf/unseen-songlist.com.conf:/etc/nginx/conf.d/default.conf:ro
  my-mysql:
    container_name: mysql-db
    image: mysql:8.0.12
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: songlist_db
      MYSQL_USER: unseenuser
      MYSQL_PASSWORD: godblessyou
      MYSQL_ROOT_PASSWORD: godblessyou
    networks:
      - spring-mysql
volumes:
  dbdata:
networks:
  spring-mysql:
