version: "3"
services:
  back-end:
    container_name: springboot-app
    build:
      context: back-end/songlist
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql-db
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/songlist_db?useSSL=false
        SPRING_DATASOURCE_USERNAME: unseenuser
        SPRING_DATASOURCE_PASSWORD: godblessyou
    networks:
      - frontend
      - backend
  front-end:
    container_name: react-app
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - back-end
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./nginx/conf/unseen-songlist.com.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend 
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.12
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: songlist_db
      MYSQL_USER: unseenuser
      MYSQL_PASSWORD: godblessyou
      MYSQL_ROOT_PASSWORD: godblessyou
    networks:
      - backend
volumes:
  dbdata:
networks:
  backend:
  frontend:
