version: "3"
services:
  back-end:
    build:
      context: back-end/songlist
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
        DB_URL: jdbc:mysql://mysql-db/songlist_db
        DB_USERNAME: unseenuser
        DB_PASSWORD: godblessyou
    depends_on:
      - my-mysql
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - back-end
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./nginx/conf/unseen-songlist.com.conf:/etc/nginx/conf.d/default.conf:ro
  my-mysql:
    image: mysql:8.0.12
    ports:
      - 3306:3306
    volumes: 
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: songlist_db
      MYSQL_USER: unseenuser
      MYSQL_PASSWORD: godblessyou
      MYSQL_ROOT_PASSWORD: godblessyou
volumes:
  dbdata:
